;;;; Copyright (c) 2026 xoCore Technologies
;;;; SPDX-License-Identifier: MIT
;;;; See LICENSE for full terms.

(def Law (Pin 1))

(def TraceOp (Pin 4))
(def syscall (Pin 5))
(def TryOp   (Pin 8))
(def WriteOp (Pin 9))
(def ReadOp  (Pin 10))
(def XPtrOp  (Pin 13))
(def XBufOp  (Pin 14))
(def PrimOp  (Pin 15))
(def SendOp  (Pin 16))
(def Error   (Pin 17))

(def xtrace
  Pin(law (xtrace m x)
    TraceOp(0 m x)))

(def xtry
  Pin(law (xtry f x)
    TryOp(0 f x)))

(def xwrite
  Pin(law (xwrite fd nat sz off)
    WriteOp(0 fd nat sz off)))

(def xread
  Pin(law (xread fd nat sz off)
    ReadOp(0 fd nat sz off)))

(def MkPin    Pin(law ("Pin" x)                 PrimOp(000 x)))
(def MkLaw    Pin(law ("Law" n a b)             PrimOp(001 n a b)))
(def Inc      Pin(law ("Inc" x)                 PrimOp(002 x)))
(def Eat      Pin(law ("Eat" p l a z m o)       PrimOp(003 p l a z m o)))
(def Force    Pin(law ("Force" x)               PrimOp(004 x)))
(def Seq      Pin(law ("Seq" a b)               PrimOp(005 a b)))
(def Sap      Pin(law ("Sap" a b)               PrimOp(006 a b)))
(def Sap2     Pin(law ("Sap2" a b c)            PrimOp(007 a b c)))
(def Sap3     Pin(law ("Sap3" a b c d)          PrimOp(008 a b c d)))
(def Sap4     Pin(law ("Sap4" a b c d e)        PrimOp(009 a b c d e)))
(def Sap5     Pin(law ("Sap5" a b c d e f)      PrimOp(010 a b c d e f)))
(def Sap6     Pin(law ("Sap6" a b c d e f g)    PrimOp(011 a b c d e f g)))
(def Sap7     Pin(law ("Sap7" a b c d e f g h)  PrimOp(012 a b c d e f g h)))
(def IsPin    Pin(law ("IsPin" x)               PrimOp(013 x)))
(def IsLaw    Pin(law ("IsLaw" x)               PrimOp(014 x)))
(def IsApp    Pin(law ("IsApp" x)               PrimOp(015 x)))
(def IsNat    Pin(law ("IsNat" x)               PrimOp(016 x)))
(def Truth    Pin(law ("Truth" x)               PrimOp(017 x)))
(def Nil      Pin(law ("Nil" x)                 PrimOp(018 x)))
(def Type     Pin(law ("Type" x)                PrimOp(019 x)))
(def Unpin    Pin(law ("Unpin" x)               PrimOp(020 x)))
(def Name     Pin(law ("Name" x)                PrimOp(021 x)))
(def Arity    Pin(law ("Arity" x)               PrimOp(022 x)))
(def Body     Pin(law ("Body" x)                PrimOp(023 x)))
(def Init     Pin(law ("Init" x)                PrimOp(024 x)))
(def Last     Pin(law ("Last" x)                PrimOp(025 x)))
(def If       Pin(law ("If" c t e)              PrimOp(026 c t e)))
(def Ifz      Pin(law ("Ifz" c t e)             PrimOp(027 c t e)))
(def Nat      Pin(law ("Nat" x)                 PrimOp(028 x)))
(def Dec      Pin(law ("Dec" x)                 PrimOp(029 x)))
(def Fresh    Pin(law ("Fresh" x)               PrimOp(030 x)))
(def And      Pin(law ("And" a b)               PrimOp(031 a b)))
(def Or       Pin(law ("Or" a b)                PrimOp(032 a b)))
(def Nand     Pin(law ("Nand" a b)              PrimOp(033 a b)))
(def Nor      Pin(law ("Nor" a b)               PrimOp(034 a b)))
(def Add      Pin(law ("Add" a b)               PrimOp("Add" a b)))
(def Sub      Pin(law ("Sub" a b)               PrimOp(036 a b)))
(def Mul      Pin(law ("Mul" a b)               PrimOp(037 a b)))
(def Pow      Pin(law ("Pow" a b)               PrimOp(038 a b)))
(def Bex      Pin(law ("Bex" x)                 PrimOp(039 x)))
(def Eq       Pin(law ("Eq" a b)                PrimOp(040 a b)))
(def Ne       Pin(law ("Ne" a b)                PrimOp(041 a b)))
(def Le       Pin(law ("Le" a b)                PrimOp(042 a b)))
(def Ge       Pin(law ("Ge" a b)                PrimOp(043 a b)))
(def Lt       Pin(law ("Lt" a b)                PrimOp(044 a b)))
(def Gt       Pin(law ("Gt" a b)                PrimOp(045 a b)))
(def Cmp      Pin(law ("Cmp" a b)               PrimOp(046 a b)))
(def Div      Pin(law ("Div" a b)               PrimOp(047 a b)))
(def Mod      Pin(law ("Mod" a b)               PrimOp(048 a b)))
(def DivMod   Pin(law ("DivMod" a b)            PrimOp(049 a b)))
(def Lsh      Pin(law ("Lsh" a b)               PrimOp(050 a b)))
(def Rsh      Pin(law ("Rsh" a b)               PrimOp(051 a b)))
(def Trunc    Pin(law ("Trunc" a b)             PrimOp(052 a b)))
(def Trunc1   Pin(law ("Trunc1" a)              PrimOp(053 a)))
(def Trunc8   Pin(law ("Trunc8" a)              PrimOp(054 a)))
(def Trunc16  Pin(law ("Trunc16" a)             PrimOp(055 a)))
(def Trunc32  Pin(law ("Trunc32" a)             PrimOp(056 a)))
(def Trunc64  Pin(law ("Trunc64" a)             PrimOp(057 a)))
(def Trunc128 Pin(law ("Trunc128" a)            PrimOp(058 a)))
(def Trunc256 Pin(law ("Trunc256" a)            PrimOp(059 a)))
(def Cut      Pin(law ("Cut" x y z)             PrimOp(060 x y z)))
(def Wipe     Pin(law ("Wipe" x y z)            PrimOp(061 x y z)))
(def Edit     Pin(law ("Edit" a b c d)          PrimOp(062 a b c d)))
(def Bits     Pin(law ("Bits" n)                PrimOp(063 n)))
(def Test     Pin(law ("Test" a b)              PrimOp(064 a b)))
(def Set      Pin(law ("Set" a b)               PrimOp(065 a b)))
(def Clear    Pin(law ("Clear" a b)             PrimOp(066 a b)))
(def Hd       Pin(law ("Hd" x)                  PrimOp(067 x)))
(def Sz       Pin(law ("Sz" v)                  PrimOp(068 v)))
(def Case     Pin(law ("Case" i r f)            PrimOp(069 i r f)))
;def Case0    Pin(law ("Case0" r f)             PrimOp(070 r f))))) ; TODO: pointle
;def Case1    Pin(law ("Case1" r f)             PrimOp(071 r f))))) ; TODO: pointle
;def Case2    Pin(law ("Case2" r f)             PrimOp(072 r f))))) ; TODO: pointle
(def Case3    Pin(law ("Case3" a b c d)         PrimOp(073 a b c d)))
(def Case4    Pin(law ("Case4" a b c d e)       PrimOp(074 a b c d e)))
(def Case5    Pin(law ("Case5" a b c d e f)     PrimOp(075 a b c d e f)))
(def Case6    Pin(law ("Case6" a b c d e f g)   PrimOp(076 a b c d e f g)))
(def Case7    Pin(law ("Case7" a b c d e f g h) PrimOp(077 a b c d e f g h)))
(def Coup     Pin(law ("Coup" x o)              PrimOp(078 x o)))
(def Up       Pin(law ("Up" i v r)              PrimOp(079 i v r)))
(def UpUniq   Pin(law ("UpUniq" i v r)          PrimOp(080 i v r)))
(def Ix       Pin(law ("Ix" i r)                PrimOp(081 i r)))
(def Ix0      Pin(law ("Ix0" r)                 PrimOp(082 r)))
(def Ix1      Pin(law ("Ix1" r)                 PrimOp(083 r)))
(def Ix2      Pin(law ("Ix2" r)                 PrimOp(084 r)))
(def Ix3      Pin(law ("Ix3" r)                 PrimOp(085 r)))
(def Ix4      Pin(law ("Ix4" r)                 PrimOp(086 r)))
(def Ix5      Pin(law ("Ix5" r)                 PrimOp(087 r)))
(def Ix6      Pin(law ("Ix6" r)                 PrimOp(088 r)))
(def Ix7      Pin(law ("Ix7" r)                 PrimOp(089 r)))
(def Rep      Pin(law ("Rep" a b c)             PrimOp(090 a b c)))
(def Row      Pin(law ("Row" a b c)             PrimOp(091 a b c)))
(def Copy     Pin(law ("Copy" a b c d e)        PrimOp(092 a b c d e)))
(def Switch   Pin(law ("Switch" a b c d)        PrimOp(093 a b c d)))
(def Bytes    Pin(law ("Bytes" s)               PrimOp(094 s)))
(def Load     Pin(law ("Load" o w n)            PrimOp(095 o w n)))
(def Erase    Pin(law ("Erase" o w n)           PrimOp(096 o w n)))
(def Store    Pin(law ("Store" o w v n)         PrimOp(097 o w v n)))
(def Splice   Pin(law ("Splice" i o n s b)      PrimOp(098 i o n s b)))
(def Load8    Pin(law ("Load8" o n)             PrimOp(099 o n)))
(def Load16   Pin(law ("Load16" o n)            PrimOp(100 o n)))
(def Load32   Pin(law ("Load32" o n)            PrimOp(101 o n)))
(def Load64   Pin(law ("Load64" o n)            PrimOp(102 o n)))
(def Store8   Pin(law ("Store8" o v n)          PrimOp(103 o v n)))
(def Store16  Pin(law ("Store16" o v n)         PrimOp(104 o v n)))
(def Store32  Pin(law ("Store32" o v n)         PrimOp(105 o v n)))
(def Store64  Pin(law ("Store64" o v n)         PrimOp(106 o v n)))
(def RefEq    Pin(law ("RefEq" a b)             PrimOp(107 a b)))

(def CopyUniq  Pin(law ("CopyUniq" a b c d e)   PrimOp(108 a b c d e)))
(def Snore     Pin(law ("Snore" a b c d e)      PrimOp(109 a b c d e)))

; TODO: make these primops

(def Seq2    Pin(law (Seq2 a b c)       (Seq a        (Seq b c))))
(def Seq3    Pin(law (Seq3 a b c d)     (Seq2 a b     (Seq c d))))
(def Seq4    Pin(law (Seq4 a b c d e)   (Seq3 a b c   (Seq d e))))
(def Seq5    Pin(law (Seq5 a b c d e f) (Seq4 a b c e (Seq e f))))
(def DeepSeq Pin(law (DeepSeq x y)      (Seq (Force x) y)))
