#!/usr/bin/env bash

# Hacked up demo script to run against the temporary single threaded direct
# syscall version of fulltag.

#
# To run the demo, just run `x/demo-full-tag` from the toplevel directory of
# the repository.
#

THREADS=16
FIRST_PAGE=1
# Use --last-page to pick a different range.

USE_LOCAL=0
USE_CDN=0
RUN_TESTS=0
CHECK_LIMITS=1
REQ_LAST_PAGE=0
MACHINE_FILE=""
MACHINE_ARGS=()
NO_START=0

usage ()
{
    echo "Usage: ./demo-full-tag [ -d | --demosrc SRCDIR ]
                                 [ --use-local | --use-cdn ]
                                 [ --ci ]
                                 [ --no-check-limits ]
                                 [ --last-page NUM ]
                                 [ --machine-file name ]
                                 [ --no-start ]
                                 [ -p | --profile-output PROF_FILE ]
                                 [ -P | --profile-laws ]

    demo-full-tag will try to download a small 600 json file demo if
    '-d' is unset.

    You can download a larger 70GB dataset that contains a million images
    by downloading this torrent:

    magnet:?xt=urn:btih:c2f603468767fc098ddb8f0d560688caa6690304&dn=safe-score-gte-37.tar.gz&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce"
    exit 2
}

PARSED_ARGUMENTS=$(
    getopt -a -n alphabet \
        -o d:p:P \
        --long demosrc:,machine-file:,no-start,profile-output:,last-page:,no-check-limits,ci,profile-laws,use-local,use-cdn,help \
        -- "$@"
)
VALID_ARGUMENTS=$?
if [ "$VALID_ARGUMENTS" != "0" ]; then
  usage
fi

#echo "PARSED_ARGUMENTS is $PARSED_ARGUMENTS"
eval set -- "$PARSED_ARGUMENTS"
while :
do
  case "$1" in
    -d | --demosrc)        DEMOSRC="$2"             ; shift 2 ;;
    --use-local)           USE_LOCAL=1              ; shift   ;;
    --use-cdn)             USE_CDN=1                ; shift   ;;
    --last-page)           REQ_LAST_PAGE="$2"       ; shift 2 ;;
    --machine-file)        MACHINE_FILE="$2"        ; shift 2 ;;
    --no-start)            NO_START=1               ; shift   ;;
    --no-check-limits)     CHECK_LIMITS=0           ; shift   ;;

    --ci)
        RUN_TESTS=1
        CHECK_LIMITS=0
        DEMOSRC=testdata/fulltag
        shift 1
        ;;

    # Don't "error" on help.
    --help) usage ;;

    # -- means the end of the arguments; drop this, and break out of the while loop
    --) shift; break ;;

    # If invalid options were passed, then getopt should have reported an error,
    # which we checked as VALID_ARGUMENTS when getopt was called...
    *) echo "Unexpected option: $1 - this should not happen."
       usage ;;
  esac
done

if [ -z "${DEMOSRC}" ]; then
    echo "Using default demo..."

    # Ensure the datadir files are downloaded. This is 600 json files to parse.
    if ! [ -f elm/full-tag-demo/datadir.tar.gz ]; then
        pushd elm/full-tag-demo
        wget -O datadir.tar.gz \
             https://www.dropbox.com/s/a9dwuiny135pk6o/datadir.tar.gz?dl=1
        mkdir -p datadir/json/
        # previous demo was just json, now requires json/img separation in the
        # big demo.
        tar xf datadir.tar.gz -C datadir/json --strip-components=1
        popd
    fi

    DEMOSRC="elm/full-tag-demo/datadir"
fi

if [ "${REQ_LAST_PAGE}" -ne 0 ]; then
    LAST_PAGE=$REQ_LAST_PAGE
else
    LAST_PAGE=$(ls "${DEMOSRC}/json" | grep -o -E '[0-9]+' | sort -n | tail -n 1)
fi

UPLOAD_IMG=0

if [ "${USE_LOCAL}" -eq 1 -a "${USE_CDN}" -eq 1 ]; then
    echo "Error: Can't both set --use-local and --use-cdn"
    exit 2
elif [ "${USE_LOCAL}" -eq 1 ]; then
    if [ -d "$DEMOSRC/img/" ]; then
        UPLOAD_IMG=1
    else
        echo "Error: Can't --use-local on a dataset without images"
        exit 2
    fi
fi

# Ensure the elm files are built.
if ! [ -f elm/full-tag-demo/elm.js ]; then
    nix-shell -p elmPackages.elm --run "cd elm/full-tag-demo && sh/build"
elif [ elm/full-tag-demo/src/Main.elm -nt ./elm/full-tag-demo/elm.js ]; then
    nix-shell -p elmPackages.elm --run "cd elm/full-tag-demo && sh/build"
fi

xseedfile=.demo-full-tag.xseed

# TODO: error out if this broke.
plunder xsave -Z --new-format $xseedfile demo_full_tag
if [ $? -ne 0 ]; then
  echo "seed file compile failed" >&2
  exit 1
fi


if [ "${NO_START}" -eq 1 ]; then
    # Do nothing. No start!
    echo "Not starting fulltag. Assuming already running."
elif [ "${MACHINE_FILE}" = "" ]; then
    x/plan $xseedfile &
    RUN_MACHINE=$!
else
    rm -f ${MACHINE_FILE}
    x/boot $xseedfile ${MACHINE_FILE}
    ./${MACHINE_FILE} &
    RUN_MACHINE=$!
fi

# cleanup () {
#     echo "Killing $RUN_MACHINE"
#     kill $RUN_MACHINE
#     wait $RUN_MACHINE
# }

# trap cleanup EXIT INT TERM

# TODO: This causes something to segfault, but it does cleanly kill everything.
trap "kill 0" EXIT INT TERM

echo "started..."

while ! nc -z localhost 8080; do
  sleep 0.1
done

PORT=8080

echo "Setting interface files..."
curl --data-binary @elm/full-tag-demo/elm.js -H "Content-Type: text/javascript" -X PUT http://localhost:$PORT/elm.js
curl --data-binary @elm/full-tag-demo/index-xmlhttprequest.html -H "Content-Type: text/html" -X PUT http://localhost:$PORT/index.html

echo "Interface files are set. Running on http://localhost:$PORT/index.html"

if [ ${UPLOAD_IMG} -eq 1 ]; then
    echo "Setting use local images only..."
    curl -X POST "http://localhost:$PORT/uselocal"
fi

echo "Sending JSON dumps..."

upload_images_for_file () {

    if [ ${UPLOAD_IMG} -ne 1 ]; then
        return
    fi

    echo "page-$i.json (IMG)"

    local FILE="$1"

    local CURL_ARGS=""

    # Get all the thumbnail URLs from the file.
    local urls=$(cat $FILE | jq -r ".images[] | .representations.thumb")

    local url
    for url in $urls; do
        local BASEURL=$(dirname $url)
        local THUMBFILE=$(basename $url)
        local ID=$(basename $BASEURL)

        # Filesystems REALLY don't like directories with hundreds of thousands
        # of files, so on disk we have a two level structure where we cap
        # things at, ie, for an $ID of 1522818, the file is at
        # `1520000/1522818/thumb.gif`.
        if [ $ID -lt "10000" ]
        then BASEDIR="0"
        else BASEDIR="$(expr $ID / 10000)0000"
        fi

        # Check file existence to work around derpicdn not always agreeing with
        # the database.
        local THUMBSRC="$DEMOSRC/img/$BASEDIR/$ID/$THUMBFILE"
        local THUMBDST="http://localhost:$PORT/img/$ID/$THUMBFILE"
        if [ -f "$THUMBSRC" ]; then
            CURL_ARGS+="-T $THUMBSRC $THUMBDST "
        fi
    done

    # Upload files 50 at a time so we get some http connection reusage.
    curl $CURL_ARGS

    # If we error, we have to hard stop this thread because otherwise we're
    # going to spam the console to the point where noone can see what happened.
    if [[ $? != 0 ]]; then
        exit -1
    fi
}

#
# Each thread takes a slice of the page-space.
#
# For example, if there are four threads, the distribution will be:
#
# thread 0: 0 4  8 12 16 ...
# thread 1: 1 5  9 13 17 ...
# thread 2: 2 6 10 14 18 ...
# thread 3: 3 7 11 15 19 ...
#
upload_pages () {
    local threadnum=$1
    local top=$(($FIRST_PAGE + $threadnum))

    local i
    for i in $(seq $top $THREADS $LAST_PAGE); do
        local FILE="$DEMOSRC/json/page-$i.json"
        local url="http://localhost:$PORT/learn";
        if [ -e "$FILE" ]
        then
            upload_images_for_file "$FILE"

            echo "page-$i.json"
            curl -d @$FILE -H "Content-Type: application/json" -X POST "$url"
            if [[ $? != 0 ]]; then
                exit -1
            fi
        fi
    done
}

last_thread=$(($THREADS - 1))

for i in $(seq 0 $last_thread); do
    upload_pages $i &
    tid[$i]=$!;
done

cleanup () {
    for i in $(seq 0 $last_thread); do
        kill ${tid[$i]} 2>/dev/null
    done
}

trap cleanup EXIT

for i in $(seq 0 $last_thread); do
    wait ${tid[$i]}
done

echo "Running on http://localhost:$PORT/index.html"

if [ $RUN_TESTS -eq 1 ]
then
    json='{"tag":"Search","contents":{"offset":0,"tags":["cute"]}}'

    sleep 0.5

    curl -XPOST http://localhost:$PORT/search -d "$json" >out.json

    cleanup () { rm -f out.json; }
    trap cleanup EXIT

    failed=0

    fail () {
        "TESTS FAILED: json output does not match expectations"
        jq . < out.json
        failed=1
    }

    test 500 -eq $(jq .status.imgs out.json)    || fail
    test 377 -eq $(jq .contents.total out.json) || fail

    if [ $failed = 0 ]; then
        echo "TEST SUCCESS: demo_full_tag_site"
    fi

    kill $RUN_MACHINE
    wait $RUN_MACHINE
    exit
fi

wait $RUN_MACHINE
